# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: node
  tag: onbuild
  pullPolicy: IfNotPresent
service:
  name: node
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
environment:
  name: CONNECTION_STRING
  secretName: my-cosmosdb-mongo-secret
  secretKey: connectionstring
